import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import {
  Container,
  Main,
  Title,
  Grid,
} from '../styles/Styles.js';
import SearchBox from './components/SearchBox.js';
import Card from './components/Card.js'


export async function getStaticProps() {
  const res = await fetch(`https://api.thecatapi.com/v1/breeds/`)
  const cats = await res.json()

  return { 
    props: { 
      cats 
    } 
  }
}

export default function Home({ cats }) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          Welcome to Cat Breeds!
        </Title>

        <SearchBox />

        <Grid>
          {cats.map((cat, i) => (
            <Link href={`/${cat.id}`}  key={i} passHref>
              <Card {...cat}>
              </Card>
            </Link>
          ))}
        </Grid>
      </Main>
    </Container>
  )
}
